name: Build Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.yml'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install markdown-to-html converter
      run: |
        npm install -g marked
        npm install -g markdown-it
        
    - name: Create web directory
      run: mkdir -p public/web
      
    - name: Build HTML documentation
      run: |
        # Create index.html from README.md
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Property Data Trust Framework Documentation</title>
            <style>
                body { 
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                    line-height: 1.6;
                    max-width: 900px;
                    margin: 0 auto;
                    padding: 2rem;
                    color: #24292e;
                }
                h1, h2, h3 { color: #0366d6; }
                code { 
                    background: #f6f8fa;
                    padding: 0.2em 0.4em;
                    border-radius: 3px;
                    font-size: 85%;
                }
                pre {
                    background: #f6f8fa;
                    padding: 16px;
                    overflow: auto;
                    border-radius: 6px;
                }
                a { color: #0366d6; text-decoration: none; }
                a:hover { text-decoration: underline; }
                .nav {
                    background: #f6f8fa;
                    padding: 1rem;
                    margin-bottom: 2rem;
                    border-radius: 6px;
                }
                .nav ul {
                    list-style: none;
                    padding: 0;
                    margin: 0;
                }
                .nav li {
                    display: inline-block;
                    margin-right: 1rem;
                }
            </style>
        </head>
        <body>
            <nav class="nav">
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="governance.html">Governance</a></li>
                    <li><a href="Draft_%20Property%20Data%20Trust%20Framework%202%20Specification.html">Framework Spec</a></li>
                    <li><a href="Draft_%20PDTF%20Participant%20DID%20Auth%20OAuth%202%20Specification.html">OAuth Spec</a></li>
                    <li><a href="../">Registry</a></li>
                </ul>
            </nav>
            <main>' > public/web/index.html
        
        # Convert README.md content
        marked README.md >> public/web/index.html
        
        echo '</main>
        </body>
        </html>' >> public/web/index.html
        
        # Build HTML for each markdown file in docs/
        for md_file in docs/*.md; do
            if [ -f "$md_file" ]; then
                filename=$(basename "$md_file" .md)
                html_file="public/web/${filename}.html"
                
                echo '<!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>'${filename}' - Property Data Trust Framework</title>
                    <style>
                        body { 
                            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                            line-height: 1.6;
                            max-width: 900px;
                            margin: 0 auto;
                            padding: 2rem;
                            color: #24292e;
                        }
                        h1, h2, h3 { color: #0366d6; }
                        code { 
                            background: #f6f8fa;
                            padding: 0.2em 0.4em;
                            border-radius: 3px;
                            font-size: 85%;
                        }
                        pre {
                            background: #f6f8fa;
                            padding: 16px;
                            overflow: auto;
                            border-radius: 6px;
                        }
                        a { color: #0366d6; text-decoration: none; }
                        a:hover { text-decoration: underline; }
                        .nav {
                            background: #f6f8fa;
                            padding: 1rem;
                            margin-bottom: 2rem;
                            border-radius: 6px;
                        }
                        .nav ul {
                            list-style: none;
                            padding: 0;
                            margin: 0;
                        }
                        .nav li {
                            display: inline-block;
                            margin-right: 1rem;
                        }
                    </style>
                </head>
                <body>
                    <nav class="nav">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><a href="governance.html">Governance</a></li>
                            <li><a href="../">Registry</a></li>
                        </ul>
                    </nav>
                    <main>' > "$html_file"
                
                # Convert markdown to HTML
                marked "$md_file" >> "$html_file"
                
                echo '</main>
                </body>
                </html>' >> "$html_file"
            fi
        done
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation-html
        path: public/web/
        
  # This job will only run on main branch pushes
  update-site:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download documentation artifacts
      uses: actions/download-artifact@v4
      with:
        name: documentation-html
        path: public/web/
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add public/web/
        git diff --staged --quiet || git commit -m "Auto-build documentation from markdown"
        git push