name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install -g marked
        
      - name: Create web directory
        run: mkdir -p public/web
        
      - name: Build HTML documentation
        run: |
          # Create index.html from README.md
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Property Data Trust Framework Documentation</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                      line-height: 1.6;
                      max-width: 900px;
                      margin: 0 auto;
                      padding: 2rem;
                      color: #24292e;
                  }
                  h1, h2, h3 { color: #0366d6; }
                  code { 
                      background: #f6f8fa;
                      padding: 0.2em 0.4em;
                      border-radius: 3px;
                      font-size: 85%;
                  }
                  pre {
                      background: #f6f8fa;
                      padding: 16px;
                      overflow: auto;
                      border-radius: 6px;
                  }
                  a { color: #0366d6; text-decoration: none; }
                  a:hover { text-decoration: underline; }
                  .nav {
                      background: #f6f8fa;
                      padding: 1rem;
                      margin-bottom: 2rem;
                      border-radius: 6px;
                  }
                  .nav ul {
                      list-style: none;
                      padding: 0;
                      margin: 0;
                  }
                  .nav li {
                      display: inline-block;
                      margin-right: 1rem;
                  }
              </style>
          </head>
          <body>
              <nav class="nav">
                  <ul>
                      <li><a href="index.html">Home</a></li>
                      <li><a href="governance.html">Governance</a></li>
                      <li><a href="plan.html">Development Plan</a></li>
                      <li><a href="Draft_%20Property%20Data%20Trust%20Framework%202%20Specification.html">Framework Spec</a></li>
                      <li><a href="Draft_%20PDTF%20Participant%20DID%20Auth%20OAuth%202%20Specification.html">OAuth Spec</a></li>
                      <li><a href="access-specification.html">Access Spec</a></li>
                      <li><a href="../">Registry</a></li>
                  </ul>
              </nav>
              <main>' > public/web/index.html
          
          # Convert README.md content
          marked README.md >> public/web/index.html
          
          echo '</main>
          </body>
          </html>' >> public/web/index.html
          
          # Build HTML for each markdown file in docs/
          for md_file in docs/*.md; do
              if [ -f "$md_file" ]; then
                  filename=$(basename "$md_file" .md)
                  html_file="public/web/${filename}.html"
                  
                  echo '<!DOCTYPE html>
                  <html lang="en">
                  <head>
                      <meta charset="UTF-8">
                      <meta name="viewport" content="width=device-width, initial-scale=1.0">
                      <title>'${filename}' - Property Data Trust Framework</title>
                      <style>
                          body { 
                              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                              line-height: 1.6;
                              max-width: 900px;
                              margin: 0 auto;
                              padding: 2rem;
                              color: #24292e;
                          }
                          h1, h2, h3 { color: #0366d6; }
                          code { 
                              background: #f6f8fa;
                              padding: 0.2em 0.4em;
                              border-radius: 3px;
                              font-size: 85%;
                          }
                          pre {
                              background: #f6f8fa;
                              padding: 16px;
                              overflow: auto;
                              border-radius: 6px;
                          }
                          a { color: #0366d6; text-decoration: none; }
                          a:hover { text-decoration: underline; }
                          .nav {
                              background: #f6f8fa;
                              padding: 1rem;
                              margin-bottom: 2rem;
                              border-radius: 6px;
                          }
                          .nav ul {
                              list-style: none;
                              padding: 0;
                              margin: 0;
                          }
                          .nav li {
                              display: inline-block;
                              margin-right: 1rem;
                          }
                      </style>
                  </head>
                  <body>
                      <nav class="nav">
                          <ul>
                              <li><a href="index.html">Home</a></li>
                              <li><a href="governance.html">Governance</a></li>
                              <li><a href="plan.html">Development Plan</a></li>
                              <li><a href="Draft_%20Property%20Data%20Trust%20Framework%202%20Specification.html">Framework Spec</a></li>
                              <li><a href="Draft_%20PDTF%20Participant%20DID%20Auth%20OAuth%202%20Specification.html">OAuth Spec</a></li>
                              <li><a href="access-specification.html">Access Spec</a></li>
                              <li><a href="../">Registry</a></li>
                          </ul>
                      </nav>
                      <main>' > "$html_file"
                  
                  # Convert markdown to HTML
                  marked "$md_file" >> "$html_file"
                  
                  echo '</main>
                  </body>
                  </html>' >> "$html_file"
              fi
          done
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4